apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev
resources:
  - ../../_base

patches:
  - path: backend/deployment.yaml
  - path: database/statefulset.yaml
  - path: networking/resources/ingress.yaml
