apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/deployment.yaml
  - backend/clusterip-service.yaml
  - database/headless-service.yaml
  - database/statefulset.yaml
  - networking/policies/deny-all-inbound.yaml
  - networking/policies/database/allow-traffic-from-backend-to-database.yaml
  - networking/policies/backend/allow-inbound-on-port-backend-is-listening-on.yaml
  - networking/resources/ingress.yaml

configMapGenerator:
  - name: backend-config
    envs:
      - configs/backend/backend-config.env

  - name: db-config
    files:
      - init.js=configs/database/init.js

secretGenerator:
  - name: app-db-secrets
    envs:
      - configs/database/app-db-creds.env

  - name: db-root-secrets
    envs:
      - configs/database/root-creds.env
