apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: color-api

spec:
  type: ClusterIP
  selector:
    app: color-api
    tier: backend

  ports:
    - port: 80
      targetPort: 80
