apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    app: color-api

spec:
  clusterIP: None
  selector:
    app: color-api
    tier: database

  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
